In [12]:
# Data exploration LLM_ABSA

In [13]:
import pandas as pd
from src.llm_absa import ABSA

# Load dataset once
df = pd.read_csv("../data/Yelp Restaurant Reviews.csv")

print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())
# print("\nSample reviews:")
# print(df['Review Text'].head(10))
df

Dataset shape: (19896, 4)
Columns: ['Yelp URL', 'Rating', 'Date', 'Review Text']

,Yelp URL,Rating,Date,Review Text
0,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,1/22/2022,All I can say is they have very good ice cream...
1,https://www.yelp.com/biz/sidney-dairy-barn-sidney,4,6/26/2022,Nice little local place for ice cream.My favor...
2,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,8/7/2021,A delicious treat on a hot day! Staff was very...
3,https://www.yelp.com/biz/sidney-dairy-barn-sidney,4,7/28/2016,This was great service and a fun crew! I got t...
4,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,6/23/2015,This is one of my favorite places to get ice c...
...,...,...,...,...
19891,https://www.yelp.com/biz/la-pasticceria-las-vegas,4,7/17/2021,Had the chocolate cannoli! The filling was ric...
19892,https://www.yelp.com/biz/la-pasticceria-las-vegas,4,10/21/2019,Love apricot croissant! I bought it at 4:00 PM...
19893,https://www.yelp.com/biz/la-pasticceria-las-vegas,4,10/12/2019,Line was about 25 people long. It went fast! T...
19894,https://www.yelp.com/biz/la-pasticceria-las-vegas,5,4/11/2021,Its hard not to order everything when I come h...
19895,https://www.yelp.com/biz/la-pasticceria-las-vegas,4,9/3/2019,Every mall needs an Eataly for real. La Pastic...

In [14]:
# Initialize analyzer
analyzer = ABSA(device='cpu')

# Run analyzer on 5 random reviews
sample_reviews = df['Review Text'].sample(5)
sample_reviews

Loading PyABSA model 'multilingual' on device: cpu
[2025-10-06 11:51:36] (2.4.2) ********** Available ATEPC model checkpoints for Version:2.4.2 (this version) **********
[2025-10-06 11:51:36] (2.4.2) ********** Available ATEPC model checkpoints for Version:2.4.2 (this version) **********
[2025-10-06 11:51:36] (2.4.2) Downloading checkpoint:multilingual
[2025-10-06 11:51:36] (2.4.2) Notice: The pretrained model are used for testing, it is recommended to train the model on your own custom datasets
[2025-10-06 11:51:36] (2.4.2) Checkpoint already downloaded, skip
FindFile Warning --> multiple targets ['checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.args.txt', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.config', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.state_dict', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.tokenizer'] found, only return the shortest path: <checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT\fast_lcf_atepc.config>
FindFile Warning --> multiple targets ['checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.args.txt', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.config', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.state_dict', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.tokenizer'] found, only return the shortest path: <checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT\fast_lcf_atepc.config>
[2025-10-06 11:51:36] (2.4.2) Load aspect extractor from checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT
[2025-10-06 11:51:36] (2.4.2) config: checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT\fast_lcf_atepc.config
[2025-10-06 11:51:36] (2.4.2) state_dict: checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT\fast_lcf_atepc.state_dict
[2025-10-06 11:51:36] (2.4.2) model: None
[2025-10-06 11:51:36] (2.4.2) tokenizer: checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT\fast_lcf_atepc.tokenizer
[2025-10-06 11:51:38] (2.4.2) Set Model Device: cpu
[2025-10-06 11:51:38] (2.4.2) Device Name: Unknown

C:\Users\phili\venvs\recommenderSystemsProject\Lib\site-packages\transformers\convert_slow_tokenizer.py:560: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
C:\Users\phili\venvs\recommenderSystemsProject\Lib\site-packages\huggingface_hub\file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

14850    I loooooooooove ice cream, it's my weakness an...
10644    This is definitely a five star establishment w...
18831    I'm 8 weeks and a couple days pregnant, so I t...
8974     Place seems pretty popular! you cannot taste t...
4274     i was very pleased with the decoration it was ...
Name: Review Text, dtype: object

In [15]:
all_results = []
for i, review in enumerate(sample_reviews, 1):
    results = analyzer.analyze(str(review))
    print(f"\nRandom Review {i}: {review}")
    for r in results:
        print("   ", r)

    all_results.append({
        "review": review,
        "aspects": [r.aspect for r in results],
        "sentiments": [r.sentiment for r in results]
    })


results_df = pd.DataFrame(all_results)
results_df

C:\Users\phili\venvs\recommenderSystemsProject\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Aspect: ice cream, Sentiment: Positive, Confidence: 0.97
Aspect: ice cream, Sentiment: Positive, Confidence: 1.00
Aspect: fishy, Sentiment: Positive, Confidence: 0.99
Aspect: texture, Sentiment: Positive, Confidence: 0.99
Aspect: location, Sentiment: Positive, Confidence: 0.88
Aspect: lines, Sentiment: Negative, Confidence: 0.98

Random Review 1: I loooooooooove ice cream, it's my weakness and the most important on my cheat days. I had somi in Cali a few years back when it first started so I was thrilled when it made its way here! The ice cream is so creamy and the fishy has the best crispy gooey texture to it. It's probably more dangerous for me because I live down the street, eek!! The plus side is this location is a little slower than China town so I don't have to turn myself away from long lines.
    AspectSentiment(aspect='ice cream', sentiment='positive', confidence=0.9696, text_span=[2, 3])
    AspectSentiment(aspect='ice cream', sentiment='positive', confidence=0.9952, text_span=[1, 2])
    AspectSentiment(aspect='fishy', sentiment='positive', confidence=0.9909, text_span=[8])
    AspectSentiment(aspect='texture', sentiment='positive', confidence=0.9949, text_span=[14])
    AspectSentiment(aspect='location', sentiment='positive', confidence=0.8767, text_span=[5])
    AspectSentiment(aspect='lines', sentiment='negative', confidence=0.9833, text_span=[25])
Aspect: establishment, Sentiment: Positive, Confidence: 1.00
Aspect: donuts, Sentiment: Positive, Confidence: 1.00
Aspect: donuts, Sentiment: Positive, Confidence: 0.65
Aspect: selection, Sentiment: Positive, Confidence: 0.66
Aspect: hot coffees, Sentiment: Positive, Confidence: 0.57
Aspect: donut, Sentiment: Positive, Confidence: 0.65

Random Review 2: This is definitely a five star establishment with some of the best donuts anywhere. From their classic, timeless glazed to the newer bacon-topped and creme-themed donuts, this westside wonder should be added to the itinerary of any northeast Ohio trip. Of course they have a selection of hot coffees, too. Go early to make sure your fresh donut hasn't been snatched by... well, me.
    AspectSentiment(aspect='establishment', sentiment='positive', confidence=0.9985, text_span=[6])
    AspectSentiment(aspect='donuts', sentiment='positive', confidence=0.9986, text_span=[12])
    AspectSentiment(aspect='donuts', sentiment='positive', confidence=0.6492, text_span=[16])
    AspectSentiment(aspect='selection', sentiment='positive', confidence=0.6597, text_span=[5])
    AspectSentiment(aspect='hot coffees', sentiment='positive', confidence=0.5683, text_span=[7, 8])
    AspectSentiment(aspect='donut', sentiment='positive', confidence=0.651, text_span=[7])
Aspect: sundae, Sentiment: Neutral, Confidence: 0.71
Aspect: cookies, Sentiment: Positive, Confidence: 0.99
Aspect: cream ice cream, Sentiment: Positive, Confidence: 0.99
Aspect: strawberry, Sentiment: Negative, Confidence: 0.69
Aspect: shake, Sentiment: Positive, Confidence: 0.77
Aspect: strawberry, Sentiment: Positive, Confidence: 1.00
Aspect: store, Sentiment: Positive, Confidence: 0.99
Aspect: socks, Sentiment: Positive, Confidence: 0.79
Aspect: candy, Sentiment: Positive, Confidence: 0.77
Aspect: ice cream, Sentiment: Positive, Confidence: 0.95
Aspect: cones, Sentiment: Neutral, Confidence: 0.98
Aspect: cups, Sentiment: Neutral, Confidence: 0.97
Aspect: sundae, Sentiment: Positive, Confidence: 0.80
Aspect: kitchen, Sentiment: Neutral, Confidence: 0.61
Aspect: ice cream, Sentiment: Positive, Confidence: 0.92
Aspect: staff, Sentiment: Positive, Confidence: 1.00

Random Review 3: I'm 8 weeks and a couple days pregnant, so I thought Vegas would be sort of a bust without the drinking and partying Super Bowl weekend. I was pleasantly surprised when I walked into Sloan's!! On my second night there, my man and I split a sundae. We had great cookies and cream ice cream, but the strawberry was TO DIE FOR. I knew I had to try a shake the next day and boy did it deliver! Literally the best strawberry I've ever had in my life. This store has tons of cute things to buy from socks to candy and they have a TON of different ways to get your ice cream fix. They have regular cones and cups, but also have a ton of different sundae options and if you have a lot of people, they even have an actual kitchen sink full of amazing ice cream! The staff is really sweet and friendly too! Can't wait to go back and try more
    AspectSentiment(aspect='sundae', sentiment='neutral', confidence=0.7134, text_span=[12])
    AspectSentiment(aspect='cookies', sentiment='positive', confidence=0.9913, text_span=[3])
    AspectSentiment(aspect='cream ice cream', sentiment='positive', confidence=0.9925, text_span=[5, 6, 7])
    AspectSentiment(aspect='strawberry', sentiment='negative', confidence=0.692, text_span=[11])
    AspectSentiment(aspect='shake', sentiment='positive', confidence=0.7745, text_span=[7])
    AspectSentiment(aspect='strawberry', sentiment='positive', confidence=0.9985, text_span=[3])
    AspectSentiment(aspect='store', sentiment='positive', confidence=0.993, text_span=[1])
    AspectSentiment(aspect='socks', sentiment='positive', confidence=0.7928, text_span=[10])
    AspectSentiment(aspect='candy', sentiment='positive', confidence=0.7657, text_span=[12])
    AspectSentiment(aspect='ice cream', sentiment='positive', confidence=0.9544, text_span=[24, 25])
    AspectSentiment(aspect='cones', sentiment='neutral', confidence=0.9785, text_span=[3])
    AspectSentiment(aspect='cups', sentiment='neutral', confidence=0.9741, text_span=[5])
    AspectSentiment(aspect='sundae', sentiment='positive', confidence=0.7979, text_span=[14])
    AspectSentiment(aspect='kitchen', sentiment='neutral', confidence=0.6101, text_span=[30])
    AspectSentiment(aspect='ice cream', sentiment='positive', confidence=0.9224, text_span=[35, 36])
    AspectSentiment(aspect='staff', sentiment='positive', confidence=0.9985, text_span=[1])
Aspect: Place, Sentiment: Positive, Confidence: 1.00
Aspect: ice cream, Sentiment: Negative, Confidence: 0.88
Aspect: cups, Sentiment: Negative, Confidence: 0.67
Aspect: ice cream, Sentiment: Negative, Confidence: 0.65
Aspect: place, Sentiment: Negative, Confidence: 0.95
Aspect: Worker, Sentiment: Negative, Confidence: 0.64
Aspect: ice cream, Sentiment: Neutral, Confidence: 0.98

Random Review 4: Place seems pretty popular! you cannot taste test the ice cream so you don't know what your getting in to! For 2 single cups of ice cream was $13 so pretty expensive. Also not the cleanest place. Worker never washed her hands or wore gloves and was touching everyone's ice cream
    AspectSentiment(aspect='Place', sentiment='positive', confidence=0.9978, text_span=[0])
    AspectSentiment(aspect='ice cream', sentiment='negative', confidence=0.8834, text_span=[5, 6])
    AspectSentiment(aspect='cups', sentiment='negative', confidence=0.6685, text_span=[3])
    AspectSentiment(aspect='ice cream', sentiment='negative', confidence=0.6464, text_span=[5, 6])
    AspectSentiment(aspect='place', sentiment='negative', confidence=0.952, text_span=[4])
    AspectSentiment(aspect='Worker', sentiment='negative', confidence=0.6448, text_span=[0])
    AspectSentiment(aspect='ice cream', sentiment='neutral', confidence=0.9797, text_span=[14, 15])
Aspect: decoration, Sentiment: Positive, Confidence: 0.96
Aspect: dessert, Sentiment: Positive, Confidence: 0.76
Aspect: caramel salted brownie, Sentiment: Positive, Confidence: 0.66
Aspect: caramel, Sentiment: Positive, Confidence: 0.68
Aspect: brae and turkey sandwich, Sentiment: Positive, Confidence: 0.84
Aspect: meal, Sentiment: Neutral, Confidence: 0.65
Aspect: place, Sentiment: Positive, Confidence: 0.99

Random Review 5: i was very pleased with the decoration it was someones living room. The dessert looked really pretty but,it was not that great at all. The caramel salted brownie was grainy and the caramel was very thick . i did however have a brae and turkey sandwich and that was the best part of my meal it was very plain just how i like it. i could see my self here again mostly because i think this is the only 24 hour place in town.
    AspectSentiment(aspect='decoration', sentiment='positive', confidence=0.9639, text_span=[6])
    AspectSentiment(aspect='dessert', sentiment='positive', confidence=0.7597, text_span=[1])
    AspectSentiment(aspect='caramel salted brownie', sentiment='positive', confidence=0.6572, text_span=[1, 2, 3])
    AspectSentiment(aspect='caramel', sentiment='positive', confidence=0.6765, text_span=[8])
    AspectSentiment(aspect='brae and turkey sandwich', sentiment='positive', confidence=0.8353, text_span=[5, 6, 7, 8])
    AspectSentiment(aspect='meal', sentiment='neutral', confidence=0.6502, text_span=[17])
    AspectSentiment(aspect='place', sentiment='positive', confidence=0.9939, text_span=[17])

,review,aspects,sentiments
0,"I loooooooooove ice cream, it's my weakness an...","[ice cream, ice cream, fishy, texture, locatio...","[positive, positive, positive, positive, posit..."
1,This is definitely a five star establishment w...,"[establishment, donuts, donuts, selection, hot...","[positive, positive, positive, positive, posit..."
2,"I'm 8 weeks and a couple days pregnant, so I t...","[sundae, cookies, cream ice cream, strawberry,...","[neutral, positive, positive, negative, positi..."
3,Place seems pretty popular! you cannot taste t...,"[Place, ice cream, cups, ice cream, place, Wor...","[positive, negative, negative, negative, negat..."
4,i was very pleased with the decoration it was ...,"[decoration, dessert, caramel salted brownie, ...","[positive, positive, positive, positive, posit..."