In [5]:
# Data exploration LLM_ABSA

In [6]:
import pandas as pd
from src.ML_ABSA import ABSA

# Load dataset once
df = pd.read_csv("../data/Yelp Restaurant Reviews.csv")

print("Dataset shape:", df.shape)
print("Columns:", df.columns.tolist())
# print("\nSample reviews:")
# print(df['Review Text'].head(10))
df

Dataset shape: (19896, 4)
Columns: ['Yelp URL', 'Rating', 'Date', 'Review Text']

,Yelp URL,Rating,Date,Review Text
0,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,1/22/2022,All I can say is they have very good ice cream...
1,https://www.yelp.com/biz/sidney-dairy-barn-sidney,4,6/26/2022,Nice little local place for ice cream.My favor...
2,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,8/7/2021,A delicious treat on a hot day! Staff was very...
3,https://www.yelp.com/biz/sidney-dairy-barn-sidney,4,7/28/2016,This was great service and a fun crew! I got t...
4,https://www.yelp.com/biz/sidney-dairy-barn-sidney,5,6/23/2015,This is one of my favorite places to get ice c...
...,...,...,...,...
19891,https://www.yelp.com/biz/la-pasticceria-las-vegas,4,7/17/2021,Had the chocolate cannoli! The filling was ric...
19892,https://www.yelp.com/biz/la-pasticceria-las-vegas,4,10/21/2019,Love apricot croissant! I bought it at 4:00 PM...
19893,https://www.yelp.com/biz/la-pasticceria-las-vegas,4,10/12/2019,Line was about 25 people long. It went fast! T...
19894,https://www.yelp.com/biz/la-pasticceria-las-vegas,5,4/11/2021,Its hard not to order everything when I come h...
19895,https://www.yelp.com/biz/la-pasticceria-las-vegas,4,9/3/2019,Every mall needs an Eataly for real. La Pastic...

In [7]:
# Initialize analyzer
analyzer = ABSA(device='cpu')

# Run analyzer on 5 random reviews
sample_reviews = df['Review Text'].sample(5)
sample_reviews

Loading PyABSA model 'english_lcf_atepc' on device: cpu
[2025-10-20 13:25:14] (2.4.2) ********** Available ATEPC model checkpoints for Version:2.4.2 (this version) **********
[2025-10-20 13:25:14] (2.4.2) ********** Available ATEPC model checkpoints for Version:2.4.2 (this version) **********
[2025-10-20 13:25:14] (2.4.2) Checkpoint:english_lcf_atepc is not found, you can raise an issue for requesting shares of checkpoints
[2025-10-20 13:25:14] (2.4.2) No checkpoint found in Model Hub for task: english_lcf_atepc
FindFile Warning --> multiple targets ['checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.args.txt', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.config', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.state_dict', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.tokenizer'] found, only return the shortest path: <checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT\fast_lcf_atepc.config>
FindFile Warning --> multiple targets ['checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.args.txt', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.config', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.state_dict', 'checkpoints\\ATEPC_MULTILINGUAL_CHECKPOINT\\fast_lcf_atepc.tokenizer'] found, only return the shortest path: <checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT\fast_lcf_atepc.config>
[2025-10-20 13:25:14] (2.4.2) Load aspect extractor from checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT
[2025-10-20 13:25:14] (2.4.2) config: checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT\fast_lcf_atepc.config
[2025-10-20 13:25:14] (2.4.2) state_dict: checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT\fast_lcf_atepc.state_dict
[2025-10-20 13:25:14] (2.4.2) model: None
[2025-10-20 13:25:14] (2.4.2) tokenizer: checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT\fast_lcf_atepc.tokenizer
[2025-10-20 13:25:14] (2.4.2) Set Model Device: cpu
[2025-10-20 13:25:14] (2.4.2) Device Name: Unknown

C:\Users\phili\venvs\recommenderSystemsProject\Lib\site-packages\transformers\convert_slow_tokenizer.py:560: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
C:\Users\phili\venvs\recommenderSystemsProject\Lib\site-packages\huggingface_hub\file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2341     Only Getting One Star, Because It Won't Let Yo...
14254    This place is a classic case of over-hyped and...
638      My sisters wanted to try this place out becaus...
12744    This was our first visit. They have a large va...
869      Very disappointing. We ordered 6 cupcakes , th...
Name: Review Text, dtype: object

In [8]:
all_results = []
for i, review in enumerate(sample_reviews, 1):
    results = analyzer.analyze(str(review))
    print(f"\nRandom Review {i}: {review}")
    for r in results:
        print("   ", r)

    all_results.append({
        "review": review,
        "aspects": [r.aspect for r in results],
        "sentiments": [r.sentiment for r in results]
    })


results_df = pd.DataFrame(all_results)
results_df

C:\Users\phili\venvs\recommenderSystemsProject\Lib\site-packages\torch\utils\data\dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Random Review 1: Only Getting One Star, Because It Won't Let You Review, Without... I Was Just Turned Away From Service, Although I Was In Line Before The Store's Posted Closing. They Turned Off The Lights, And Made An Announcement That The Woman In Front Of Me Was Last... It Was Very Poor Customer Service, And You May Want To Retrain Your Staff... They Were Having Fun, Visibly Goofing Off, Inside. Hence The Line Not Moving. As I'm Writing This, The Line Has Yet To Be Completed. I Would Be Ashamed If This Was My Store.
    AspectSentiment(aspect='Review', sentiment='neutral', confidence=0.5553, text_span=[12])
    AspectSentiment(aspect='Service', sentiment='negative', confidence=0.9763, text_span=[6])
    AspectSentiment(aspect='Lights', sentiment='neutral', confidence=0.8613, text_span=[4])
    AspectSentiment(aspect='Customer Service', sentiment='negative', confidence=0.9966, text_span=[4, 5])
    AspectSentiment(aspect='Staff', sentiment='negative', confidence=0.9379, text_span=[14])
    AspectSentiment(aspect='Line', sentiment='negative', confidence=0.9962, text_span=[2])
    AspectSentiment(aspect='Line', sentiment='negative', confidence=0.9126, text_span=[8])
    AspectSentiment(aspect='Store', sentiment='negative', confidence=0.9963, text_span=[8])

Random Review 2: This place is a classic case of over-hyped and under-delivered. The cereal flavored soft serve was honestly quite gross. I tried 3 different types of cookies, and not one of them was noteworthy. Not worth the visit!
    AspectSentiment(aspect='place', sentiment='negative', confidence=0.9949, text_span=[1])
    AspectSentiment(aspect='cereal', sentiment='negative', confidence=0.7476, text_span=[1])
    AspectSentiment(aspect='serve', sentiment='negative', confidence=0.8162, text_span=[4])
    AspectSentiment(aspect='cookies', sentiment='negative', confidence=0.6712, text_span=[6])
    AspectSentiment(aspect='visit', sentiment='negative', confidence=0.9969, text_span=[3])

Random Review 3: My sisters wanted to try this place out because we are all fans of Cake Boss and Buddy and his family. They tell you the line is about 20 minutes... ummm... you mean over an hour. I was able to go all the way to Wynn, buy something and the LV store and come back when my sisters where just hitting the counter. Good for me, bad for them. You order, then you have to wait to pay. They will call you over to confirm your order once they box it up. Too bad I didn't notice that two of the rugelach cookies were burnt...as in, you should have dumped these cookies in the trash can rather than putting it out to sell - especially @ $12.99 lb! I felt RIPPED OFF. They were running out of Lobster tails - and the person behind us was asked when they were confirming her order if she would mind having two lobster tails removed from her order - I think they oversold - there's a lag between taking customer's orders and filling them which can create issues like this. Skip Carlo's and go to another bakery if you are in this area - Hello, you are in Vegas and there's LOTS of other places to try (Thankfully) and Buddy, I watch your show Buddy's Bakery Rescue and you might want to go to this location and rescue it... I'm just sayin'.....!
    AspectSentiment(aspect='place', sentiment='positive', confidence=0.9932, text_span=[6])
    AspectSentiment(aspect='Cake', sentiment='positive', confidence=0.996, text_span=[14])
    AspectSentiment(aspect='line', sentiment='negative', confidence=0.975, text_span=[4])
    AspectSentiment(aspect='counter', sentiment='neutral', confidence=0.9807, text_span=[27])
    AspectSentiment(aspect='box', sentiment='neutral', confidence=0.9332, text_span=[11])
    AspectSentiment(aspect='rugelach', sentiment='negative', confidence=0.9943, text_span=[11])
    AspectSentiment(aspect='trash', sentiment='negative', confidence=0.9844, text_span=[29])
    AspectSentiment(aspect='Lobster tails', sentiment='negative', confidence=0.8723, text_span=[5, 6])
    AspectSentiment(aspect='lobster', sentiment='negative', confidence=0.967, text_span=[27])

Random Review 4: This was our first visit. They have a large variety of items and a nice little area to eat outdoors. We tried several different items and all agreed that the Vanilla Swirl was the best. The items are about $3.00 a piece.
    AspectSentiment(aspect='visit', sentiment='neutral', confidence=0.9696, text_span=[4])
    AspectSentiment(aspect='items', sentiment='positive', confidence=0.9937, text_span=[6])
    AspectSentiment(aspect='area', sentiment='positive', confidence=0.923, text_span=[11])
    AspectSentiment(aspect='items', sentiment='neutral', confidence=0.5431, text_span=[4])
    AspectSentiment(aspect='Vanilla Swirl', sentiment='positive', confidence=0.9928, text_span=[10, 11])
    AspectSentiment(aspect='items', sentiment='neutral', confidence=0.8823, text_span=[1])

Random Review 5: Very disappointing. We ordered 6 cupcakes , the icing is horrible . Took them home to my kids because they are huge fans of the cake boss and we were very disappointed.
    AspectSentiment(aspect='cupcakes', sentiment='neutral', confidence=0.9866, text_span=[3])
    AspectSentiment(aspect='icing', sentiment='negative', confidence=0.9556, text_span=[6])
    AspectSentiment(aspect='cake', sentiment='negative', confidence=0.673, text_span=[13])

,review,aspects,sentiments
0,"Only Getting One Star, Because It Won't Let Yo...","[Review, Service, Lights, Customer Service, St...","[neutral, negative, neutral, negative, negativ..."
1,This place is a classic case of over-hyped and...,"[place, cereal, serve, cookies, visit]","[negative, negative, negative, negative, negat..."
2,My sisters wanted to try this place out becaus...,"[place, Cake, line, counter, box, rugelach, tr...","[positive, positive, negative, neutral, neutra..."
3,This was our first visit. They have a large va...,"[visit, items, area, items, Vanilla Swirl, items]","[neutral, positive, positive, neutral, positiv..."
4,"Very disappointing. We ordered 6 cupcakes , th...","[cupcakes, icing, cake]","[neutral, negative, negative]"